# Generated by Django 2.2.5 on 2020-09-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200914_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_high', models.PositiveIntegerField(default=0)),
                ('p_medium', models.PositiveIntegerField(default=0)),
                ('p_low', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
